In [1]:
# Tutorial 3
# Needleman Wunsch Algorith
# Andrew Mullen

# Import Modules
import numpy as np
import pandas as pd

In [2]:
# Define Function
def needleAlg(s1, s2, match, gap, mismatch) :
    N = len(s1)
    M = len(s2)
    
    mx = np.zeros((N+1, M+1))
    
    for i in range(1,N+1) :
        mx[i,0] = mx[i-1,0] + gap
        
    for j in range(1,M+1) :
        mx[0,j] = mx[0,j-1] + gap
             
    for i in range(1,N+1) :
        for j in range(1,M+1) :
            if s1[i-1] == s2[j-1] :
                score1 = mx[i-1,j-1] + match
            else :
                score1 = mx[i-1,j-1] + mismatch
                
            score2 = mx[i,j-1] + gap
            score3 = mx[i-1,j] + gap
                
            mx[i,j] = max(score1, score2, score3)

    return mx, N, M

def buildDirectionalString(mx, N, M, gap) :
    dstring = ""
    
    currentRow = N
    currentCol = M
    
    while(currentRow != 0 and currentCol != 0) :
        
        if currentRow == 0 :
            dstring += 'H'
            currentCol -= 1
            
        elif currentCol == 0 :
            dstring += 'V'
            currentRow -= 1
            
        elif mx[currentRow, currentCol-1] + gap == mx[currentRow, currentCol] :
            dstring += 'H'
            currentCol -= 1
            
        elif mx[currentRow-1, currentCol] + gap == mx[currentRow, currentCol] :
            dstring += 'V'
            currentRow -= 1
        
        else :
            dstring += 'D'
            currentRow -= 1
            currentCol -= 1
            
    return dstring

def buildAlignment(dstring, s1, s2, N, M) :
    s1pos = N-1
    s2pos = M-1
    dirpos = 0
    s1Align = ''
    s2Align = ''
    matchLine = ''
    dstringLen = len(dstring)
    
    while dirpos < dstringLen :
        if dstring[dirpos] == 'D' :
            if s1[s1pos] == s2[s2pos] :
                matchLine += '|'
            else :
                matchLine += ' '
            s1Align += s1[s1pos]
            s2Align += s2[s2pos]
            s1pos -= 1
            s2pos -= 1
            dirpos += 1
            
        elif dstring[dirpos] == 'V' :
            matchLine += ' '
            s1Align += s1[s1pos]
            s2Align += '-'
            s1pos -= 1
            dirpos += 1
            
        else :
            matchLine += ' '
            s1Align += '-'
            s2Align += s2[s2pos]
            s2pos -= 1
            dirpos += 1
            
    percentId = matchLine.count('|')/dstringLen
    percentGap = (s1Align.count('-')+s2Align.count('-'))/dstringLen
            
    return s1Align[::-1], matchLine[::-1], s2Align[::-1], percentId*100, percentGap*100
            

In [3]:
# Initialize Variables
s1 = 'GTTGCG'
s2 = 'ATCGACG'
match = 1
gap = -1 
mismatch = 0

# Call Functions
matrix, N, M = needleAlg(s1, s2, match, gap, mismatch)
dstring = buildDirectionalString(matrix, N, M, gap)
alignment = buildAlignment(dstring, s1, s2, N, M)

# Print Results
print('Needleman Wunsch Alignment Matrix:')
print(matrix)
print('\nDirectional String:')
print(dstring[::-1])
print('\nAlignment:')
print(alignment[0])
print(alignment[1])
print(alignment[2])
print('\nPercent ID:', alignment[3], '\nPercent Gap:', alignment[4])

Needleman Wunsch Alignment Matrix:
[[ 0. -1. -2. -3. -4. -5. -6. -7.]
 [-1.  0. -1. -2. -2. -3. -4. -5.]
 [-2. -1.  1.  0. -1. -2. -3. -4.]
 [-3. -2.  0.  1.  0. -1. -2. -3.]
 [-4. -3. -1.  0.  2.  1.  0. -1.]
 [-5. -4. -2.  0.  1.  2.  2.  1.]
 [-6. -5. -3. -1.  1.  1.  2.  3.]]

Directional String:
DDDDHDD

Alignment:
GTTG-CG
 | | ||
ATCGACG

Percent ID: 57.14285714285714 
Percent Gap: 14.285714285714285


In [4]:
# Read in sequences
s1File = open('short1.txt')
file = s1File.readline()
s1 = s1File.read()
s1 = s1.replace('\n', '')

s2File = open('short2.txt')
file = s2File.readline()
s2 = s2File.read()
s2 = s2.replace('\n', '')

# Initialize Values
gap = -1
match = 1
mismatch = 0

# Call Functions
matrix, N, M = needleAlg(s1, s2, match, gap, mismatch)
dstring = buildDirectionalString(matrix, N, M, gap)
alignment = buildAlignment(dstring, s1, s2, N, M)

# Print Results
print('Needleman Wunsch Alignment Matrix:')
print(matrix)
print('\nDirectional String:')
print(dstring[::-1])
print('\nAlignment:')
print(alignment[0])
print(alignment[1])
print(alignment[2])
print('\nPercent ID:', alignment[3], '\nPercent Gap:', alignment[4])

Needleman Wunsch Alignment Matrix:
[[  0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10. -11. -12. -13.
  -14.]
 [ -1.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10. -11.
  -12.]
 [ -2.   0.   2.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9.
  -10.]
 [ -3.  -1.   1.   3.   2.   1.   0.  -1.  -2.  -3.  -4.  -5.  -6.  -7.
   -8.]
 [ -4.  -2.   0.   2.   3.   2.   2.   1.   0.  -1.  -2.  -3.  -4.  -5.
   -6.]
 [ -5.  -3.  -1.   1.   2.   3.   2.   3.   2.   1.   0.  -1.  -2.  -3.
   -4.]
 [ -6.  -4.  -2.   0.   1.   2.   3.   2.   4.   3.   2.   1.   0.  -1.
   -2.]
 [ -7.  -5.  -3.  -1.   0.   1.   2.   3.   3.   5.   4.   3.   2.   1.
    0.]
 [ -8.  -6.  -4.  -2.  -1.   0.   2.   2.   3.   4.   6.   5.   4.   3.
    2.]
 [ -9.  -7.  -5.  -3.  -2.  -1.   1.   3.   2.   3.   5.   7.   6.   5.
    4.]
 [-10.  -8.  -6.  -4.  -2.  -1.   0.   2.   3.   2.   4.   6.   8.   7.
    6.]
 [-11.  -9.  -7.  -5.  -3.  -1.  -1.   1.   2.   3.   3.   5.   7.   9.
    8.]
 [-12

In [5]:
# Read in sequences
sHFile = open('sHumanLDL.txt')
file = sHFile.readline()
H1 = sHFile.read()
H1 = H1.replace('\n', '')

sMFile = open('sMouseLDL.txt')
file = sMFile.readline()
M1 = sMFile.read()
M1 = M1.replace('\n', '')

# Divide mouse and human sequences
M2 = M1[1900:2045]
H2 = H1[21:166]

# Save to files
M2file = open("M2seq.txt", "w+")
M2file.write(M2)
M2file.close()

H2file = open("H2seq.txt", "w+")
H2file.write(H2)
H2file.close()

In [6]:
len(H2)

145

In [7]:
# Initialize Values
gap = -1
match = 1
mismatch = 0

# Call Functions
matrix, N, M = needleAlg(M2, H1, match, gap, mismatch)
dstring = buildDirectionalString(matrix, N, M, gap)
alignment = buildAlignment(dstring, M2, H1, N, M)

# Print Results
print('Needleman Wunsch Alignment Matrix:')
print(matrix)
print('\nDirectional String:')
print(dstring[::-1])
print('\nAlignment:')
print(alignment[0][0:114])
print(alignment[1][0:114])
print(alignment[2][0:114])
print('\nAlignment Continued:')
print(alignment[0][114:])
print(alignment[1][114:])
print(alignment[2][114:])
print('\nPercent ID:', alignment[3], '\nPercent Gap:', alignment[4])

Needleman Wunsch Alignment Matrix:
[[   0.   -1.   -2. ... -180. -181. -182.]
 [  -1.    0.    0. ... -178. -179. -180.]
 [  -2.    0.    0. ... -176. -177. -178.]
 ...
 [-143. -141. -139. ...   92.   91.   91.]
 [-144. -142. -140. ...   94.   93.   92.]
 [-145. -143. -141. ...   95.   95.   94.]]

Directional String:
DDHHHHDDHHDHDHHHHHHHDDHHHDHDDDHHDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDHHHDHHDDHHHHHHDHDHHHDH

Alignment:
CT----AG--A-T-------CT---T-TCC--AGTGGCCGTCTCTATTGGGTTGATTCCAAACTCCACTCTATCTCCAGCATCGATGTCAATGGGGGCAATCGGAAAACCATTT
||    |   | |       ||   | |||  |||||||| ||||| |||||||| |||||||| ||||| ||||| ||||||||||||||||||||||| ||||| ||||| |
CTCCTTATCCACTTGTGTGTCTAGATCTCCTCAGTGGCCGCCTCTACTGGGTTGACTCCAAACTTCACTCCATCTCAAGCATCGATGTCAATGGGGGCAACCGGAAGACCATCT

Alignment Continued:
TGGAGGATGAGAACCGGCTGGCCCACCCCTTCTCCTTGGCCATCT---A--TG------A-G---G-
|||||||||| ||  |||||||||||||||||||||||||| |||   |  

In [8]:
# Initialize Values
gap = -1
match = 1
mismatch = 0

# Call Functions
matrix, N, M = needleAlg(M2, H2, match, gap, mismatch)
dstring = buildDirectionalString(matrix, N, M, gap)
alignment = buildAlignment(dstring, M2, H2, N, M)

# Print Results
print('Needleman Wunsch Alignment Matrix:')
print(matrix)
print('\nDirectional String:')
print(dstring[::-1])
print('\nAlignment:')
print(alignment[0][0:114])
print(alignment[1][0:114])
print(alignment[2][0:114])
print('\nAlignment Continued:')
print(alignment[0][114:])
print(alignment[1][114:])
print(alignment[2][114:])
print('\nPercent ID:', alignment[3], '\nPercent Gap:', alignment[4])

Needleman Wunsch Alignment Matrix:
[[   0.   -1.   -2. ... -143. -144. -145.]
 [  -1.    1.    0. ... -141. -142. -143.]
 [  -2.    0.    2. ... -139. -140. -141.]
 ...
 [-143. -141. -139. ...  126.  125.  124.]
 [-144. -142. -140. ...  125.  127.  126.]
 [-145. -143. -141. ...  124.  126.  128.]]

Directional String:
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

Alignment:
CTAGATCTTTCCAGTGGCCGTCTCTATTGGGTTGATTCCAAACTCCACTCTATCTCCAGCATCGATGTCAATGGGGGCAATCGGAAAACCATTTTGGAGGATGAGAACCGGCTG
||||||||   ||||||||| ||||| |||||||| |||||||| ||||| ||||| ||||||||||||||||||||||| ||||| ||||| ||||||||||| ||  |||||
CTAGATCTCCTCAGTGGCCGCCTCTACTGGGTTGACTCCAAACTTCACTCCATCTCAAGCATCGATGTCAATGGGGGCAACCGGAAGACCATCTTGGAGGATGAAAAGAGGCTG

Alignment Continued:
GCCCACCCCTTCTCCTTGGCCATCTATGAGG
||||||||||||||||||||| ||| |||||
GCCCACCCCTTCTCCTTGGCCGTCTTTGAGG

Percent ID: 88.27586206896552 
Percent Gap: 0.0
